remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Luis Bayley's - Data Analytics Portfolio
description:
  - A collection of self made Data Analytics projects using programs such as Excel, SQL, Python, and Tableau.
  - "[Linkedin](https://www.linkedin.com/in/lomfb/)"
  - "Click [here](https://docs.google.com/uc?export=download&id=1xdENqbvNmsKp4ZI-mbpGBYrVztwz5vSF) to download my CV"
baseurl: ""
url: "https://lofmb.github.io/"
show_downloads: true
#logo: /assets/Logo_No_3.PNG
