remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

# Additional configurations if needed
title: My Portfolio
description: > # this means to ignore newlines until "baseurl:"
  My awesome portfolio site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lofmb.github.io/" # the base hostname & protocol for your site
